### PR TITLE
Needed these changes for the template to build

### PR DESCRIPTION
**Pull request by auslavs**
Just started trying out farmer and needed these changes for the template to build.
Apologies if I'm doing something wrong here, this is my first time engaging in OSS.

### CODE REVIEW

**Comment by isaacabraham** [comment]
Thank you - perfect :-)

**Comment by isaacabraham** [comment]
As a second PR ;-) you could add an `open Farmer.Builders` if you wanted - this is basically the replacement for `Farmer.Resources` and automatically gives access to every builder.

**Comment by isaacabraham** [comment]
I think I have to fix a few things with the template really - especially the Azure arguments.

**Comment by auslavs** [comment]
No problem, sent through a pull request

**Pull request merged**
